# Generated by Django 4.0.6 on 2022-07-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadVideo', '0002_alter_videodetails_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodetails',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
