# Generated by Django 4.0.6 on 2022-07-20 04:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadVideo', '0003_alter_videodetails_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivevideo',
            name='video',
            field=models.FileField(upload_to='video/%y', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='videodetails',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
