# Generated by Django 4.0.6 on 2022-07-21 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadVideo', '0006_remove_calculatepricing_video_duration_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalculatePricing',
        ),
    ]
